In [1]:
import pandas as pd # importing pandas as pd
import numpy  as np # importing numpy as np

In [2]:
nums = [1, 2, 3,4 ,5]

In [6]:
s = pd.Series(nums)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums, index=[2, 4, 6, 8, 10])
print(s)

2     1
4     2
6     3
8     4
10    5
dtype: int64

In [11]:
fruits = ['Orange','Banana','Mango']
fruits = pd.Series(fruits, index=[1, 2, 3])
print(fruits)

1    Orange
2    Banana
3     Mango
dtype: object

In [12]:
dct = {'name':'Asabeneh','country':'Finland','city':'Helsinki'}

In [15]:
s = pd.Series(dct)
print(s)

name       Asabeneh
country     Finland
city       Helsinki
dtype: object

In [16]:
s = pd.Series(10, index = [1, 2, 3])
print(s)

1    10
2    10
3    10
dtype: int64

In [17]:
s = pd.Series(np.linspace(5, 20, 10)) # linspace(starting, end, items)
print(s)

0     5.000000
1     6.666667
2     8.333333
3    10.000000
4    11.666667
5    13.333333
6    15.000000
7    16.666667
8    18.333333
9    20.000000
dtype: float64

In [19]:
data = [
    ['Asabeneh', 'Finland', 'Helsink'],
    ['David', 'UK', 'London'],
    ['John', 'Sweden', 'Stockholm']
]
df = pd.DataFrame(data,index=[1,2,3], columns=['Names','Country','City'])
print(df)

      Names  Country       City
1  Asabeneh  Finland    Helsink
2     David       UK     London
3      John   Sweden  Stockholm

In [20]:
data = {'Name': ['Asabeneh', 'David', 'John'], 'Country':[
    'Finland', 'UK', 'Sweden'], 'City': ['Helsiki', 'London', 'Stockholm']}
df = pd.DataFrame(data)
print(df)

       Name  Country       City
0  Asabeneh  Finland    Helsiki
1     David       UK     London
2      John   Sweden  Stockholm

In [21]:
data = [
    {'Name': 'Asabeneh', 'Country': 'Finland', 'City': 'Helsinki'},
    {'Name': 'David', 'Country': 'UK', 'City': 'London'},
    {'Name': 'John', 'Country': 'Sweden', 'City': 'Stockholm'}]
df = pd.DataFrame(data)
print(df)

       Name  Country       City
0  Asabeneh  Finland   Helsinki
1     David       UK     London
2      John   Sweden  Stockholm

In [26]:
!curl -O https://raw.githubusercontent.com/Asabeneh/30-Days-Of-Python/master/data/weight-height.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  418k  100  418k    0     0   784k      0 --:--:-- --:--:-- --:--:--  787k

In [28]:
with open("weight-height.csv", "r", encoding="utf-8") as f:
    text = f.read()

In [29]:
print(text[:10])

"Gender","

In [30]:
import pandas as pd

df = pd.read_csv('weight-height.csv')
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [32]:
print(df.head(10)) # give five rows we can increase the number of rows by passing argument to the head() method

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156
6   Male  68.785081  183.927889
7   Male  68.348516  167.971110
8   Male  67.018950  175.929440
9   Male  63.456494  156.399676

In [33]:
print(df.tail()) # tails give the last five rows, we can increase the rows by passing argument to tail method

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [35]:
print(df.shape)

(10000, 3)

In [36]:
print(df.columns)

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [37]:
heights = df['Height'] # this is now a series

In [38]:
print(heights)

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [39]:
weights = df['Weight'] # this is now a series
print(weights)

0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...
9995    136.777454
9996    170.867906
9997    128.475319
9998    163.852461
9999    113.649103
Name: Weight, Length: 10000, dtype: float64

In [40]:
print(len(heights) == len(weights))

True

In [41]:
print(heights.describe()) # give statistical information about height data

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: Height, dtype: float64

In [42]:
print(df.describe()) # give statistical information about height data

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [44]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  10000 non-null  object
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB
None

In [45]:
import pandas as pd
import numpy as np
data = [
    {"Name": "Asabeneh", "Country":"Finland","City":"Helsinki"},
    {"Name": "David", "Country":"UK","City":"London"},
    {"Name": "John", "Country":"Sweden","City":"Stockholm"}]
df = pd.DataFrame(data)
print(df)

       Name  Country       City
0  Asabeneh  Finland   Helsinki
1     David       UK     London
2      John   Sweden  Stockholm

In [46]:
weights = [74, 78, 69]
df['Weight'] = weights
df

       Name  Country       City  Weight
0  Asabeneh  Finland   Helsinki      74
1     David       UK     London      78
2      John   Sweden  Stockholm      69

In [47]:
heights = [173, 175, 169]
df['Height'] = heights
print(df)

       Name  Country       City  Weight  Height
0  Asabeneh  Finland   Helsinki      74     173
1     David       UK     London      78     175
2      John   Sweden  Stockholm      69     169

In [48]:
df['Height'] = df['Height'] * 0.01
df

       Name  Country       City  Weight  Height
0  Asabeneh  Finland   Helsinki      74    1.73
1     David       UK     London      78    1.75
2      John   Sweden  Stockholm      69    1.69

In [49]:
# Using functions makes our code clean, but you can calculate the bmi without one
def calculate_bmi ():
    weights = df['Weight']
    heights = df['Height']
    bmi = []
    for w,h in zip(weights, heights):
        b = w/(h*h)
        bmi.append(b)
    return bmi

bmi = calculate_bmi()

In [54]:
df['BMI'] = bmi
df

       Name  Country       City  Weight  Height        BMI
0  Asabeneh  Finland   Helsinki      74    1.73  24.725183
1     David       UK     London      78    1.75  25.469388
2      John   Sweden  Stockholm      69    1.69  24.158818

In [56]:
df['BMI'] = round(df['BMI'], 1)
print(df)

       Name  Country       City  Weight  Height   BMI
0  Asabeneh  Finland   Helsinki      74    1.73  24.7
1     David       UK     London      78    1.75  25.5
2      John   Sweden  Stockholm      69    1.69  24.2

In [59]:
birth_year = ['1769', '1985', '1990']
current_year = pd.Series(2026, index=[0, 1, 2])
df['Birth Year'] = birth_year
df['Current Year'] = current_year
df

       Name  Country       City  Weight  Height   BMI Birth Year  Current Year
0  Asabeneh  Finland   Helsinki      74    1.73  24.7       1769          2026
1     David       UK     London      78    1.75  25.5       1985          2026
2      John   Sweden  Stockholm      69    1.69  24.2       1990          2026

In [60]:
print(df.Weight.dtype)

int64

In [61]:
df['Birth Year'].dtype # it gives string object , we should change this to number

dtype('O')

In [62]:
df['Birth Year'] = df['Birth Year'].astype('int')
print(df['Birth Year'].dtype) # let's check the data type now

int64

In [63]:
df['Current Year'] = df['Current Year'].astype('int')
df['Current Year'].dtype

dtype('int64')

In [64]:
ages = df['Current Year'] - df['Birth Year']
ages

0    257
1     41
2     36
dtype: int64

In [66]:
df['Age'] = ages
print(df)

       Name  Country       City  Weight  Height   BMI  Birth Year  \
0  Asabeneh  Finland   Helsinki      74    1.73  24.7        1769
1     David       UK     London      78    1.75  25.5        1985
2      John   Sweden  Stockholm      69    1.69  24.2        1990

   Current Year  Age
0          2026  257
1          2026   41
2          2026   36

In [68]:
print(df[df['Age'] > 120])

       Name  Country      City  Weight  Height   BMI  Birth Year  \
0  Asabeneh  Finland  Helsinki      74    1.73  24.7        1769

   Current Year  Age
0          2026  257

In [69]:
print(df[df['Age'] < 120])

    Name Country       City  Weight  Height   BMI  Birth Year  Current Year  \
1  David      UK     London      78    1.75  25.5        1985          2026
2   John  Sweden  Stockholm      69    1.69  24.2        1990          2026

   Age
1   41
2   36

In [70]:
!curl http://localhost:8888/files/Downloads/30-Days-Of-Python-master/30-Days-Of-Python-master/data/hacker_news.csv?_xsrf=2%7Cfbdb17f9%7C63c09c21aef5c4aad523a35c35566c2c%7C1784063182

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

In [74]:
with open('hacker_news.csv', 'r', encoding='utf-8') as f:
    text = f.readline()
print(text[:5])

id,ti

In [75]:
import pandas as pd
df = pd.read_csv('hacker_news.csv')
print(df)

             id                                              title  \
0      12224879                          Interactive Dynamic Video
1      11964716  Florida DJs May Face Felony for April Fools' W...
2      11919867       Technology ventures: From Idea to Enterprise
3      10301696  Note by Note: The Making of Steinway L1037 (2007)
4      10482257  Title II kills investment? Comcast and other I...
...         ...                                                ...
20094  12379592  How Purism Avoids Intels Active Management Tec...
20095  10339284          YC Application Translated and Broken Down
20096  10824382  Microkernels are slow and Elvis didn't do no d...
20097  10739875                      How Product Hunt really works
20098  11680777  RoboBrowser: Your friendly neighborhood web sc...

                                                     url  num_points  \
0                http://www.interactivedynamicvideo.com/         386
1      http://www.thewire.com/entertainment/2013/04/f...           2
2      https://www.amazon.com/Technology-Ventures-Ent...           3
3      http://www.nytimes.com/2007/11/07/movies/07ste...           8
4      http://arstechnica.com/business/2015/10/comcas...          53
...                                                  ...         ...
20094  https://puri.sm/philosophy/how-purism-avoids-i...          10
20095  https://medium.com/@zreitano/the-yc-applicatio...           4
20096  http://blog.darknedgy.net/technology/2016/01/0...         169
20097  https://medium.com/@benjiwheeler/how-product-h...         695
20098              https://github.com/jmcarp/robobrowser         182

       num_comments         author        created_at
0                52       ne0phyte    8/4/2016 11:52
1                 1       vezycash   6/23/2016 22:20
2                 1        hswarna    6/17/2016 0:01
3                 2     walterbell    9/30/2015 4:12
4                22         Deinos   10/31/2015 9:48
...             ...            ...               ...
20094             6  AdmiralAsshat    8/29/2016 2:22
20095             1       zreitano   10/6/2015 14:57
20096           132    vezzy-fnord     1/2/2016 0:49
20097           222          brw12  12/15/2015 19:32
20098            58      pmoriarty    5/12/2016 1:43

[20099 rows x 7 columns]

In [76]:
print(df.head())

         id                                              title  \
0  12224879                          Interactive Dynamic Video
1  11964716  Florida DJs May Face Felony for April Fools' W...
2  11919867       Technology ventures: From Idea to Enterprise
3  10301696  Note by Note: The Making of Steinway L1037 (2007)
4  10482257  Title II kills investment? Comcast and other I...

                                                 url  num_points  \
0            http://www.interactivedynamicvideo.com/         386
1  http://www.thewire.com/entertainment/2013/04/f...           2
2  https://www.amazon.com/Technology-Ventures-Ent...           3
3  http://www.nytimes.com/2007/11/07/movies/07ste...           8
4  http://arstechnica.com/business/2015/10/comcas...          53

   num_comments      author       created_at
0            52    ne0phyte   8/4/2016 11:52
1             1    vezycash  6/23/2016 22:20
2             1     hswarna   6/17/2016 0:01
3             2  walterbell   9/30/2015 4:12
4            22      Deinos  10/31/2015 9:48

In [77]:
print(df.tail())

             id                                              title  \
20094  12379592  How Purism Avoids Intels Active Management Tec...
20095  10339284          YC Application Translated and Broken Down
20096  10824382  Microkernels are slow and Elvis didn't do no d...
20097  10739875                      How Product Hunt really works
20098  11680777  RoboBrowser: Your friendly neighborhood web sc...

                                                     url  num_points  \
20094  https://puri.sm/philosophy/how-purism-avoids-i...          10
20095  https://medium.com/@zreitano/the-yc-applicatio...           4
20096  http://blog.darknedgy.net/technology/2016/01/0...         169
20097  https://medium.com/@benjiwheeler/how-product-h...         695
20098              https://github.com/jmcarp/robobrowser         182

       num_comments         author        created_at
20094             6  AdmiralAsshat    8/29/2016 2:22
20095             1       zreitano   10/6/2015 14:57
20096           132    vezzy-fnord     1/2/2016 0:49
20097           222          brw12  12/15/2015 19:32
20098            58      pmoriarty    5/12/2016 1:43

In [78]:
title = pd.Series(df['title'])

In [79]:
print(title)

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: object

In [86]:
print(df[df['title'].str.contains(r'python', case=False, regex=True)])

             id                                              title  \
102    10974870                From Python to Lua: Why We Switched
103    11244541          Ubuntu 16.04 LTS to Ship Without Python 2
144    10963528  Create a GUI Application Using Qt and Python i...
196    10716331  How I Solved GCHQ's Xmas Card with Python and ...
436    11895088  Unikernel Power Comes to Java, Node.js, Go, an...
...         ...                                                ...
19597  12061177  David Beazley  Python Concurrency from the Gro...
19852  10988468    Ask HN: How to automate Python apps deployment?
19862  11738470                          Moving Away from Python 2
19980  12524656                      Python vs. Julia Observations
19998  11735438  Show HN: Decorating: Animated pulsed for your ...

                                                     url  num_points  \
102    https://www.distelli.com/blog/using-lua-for-ou...         243
103    http://news.softpedia.com/news/ubuntu-16-04-lt...           2
144                        http://digitalpeer.com/s/c63e          21
196    http://matthewearl.github.io/2015/12/10/gchq-x...           6
436    http://www.infoworld.com/article/3082051/open-...           3
...                                                  ...         ...
19597        https://www.youtube.com/watch?v=MCs5OvhV9S4           2
19852                                                NaN           4
19862  https://asmeurer.github.io/blog/posts/moving-a...         227
19980  https://medium.com/@Jernfrost/python-vs-julia-...           2
19998             https://github.com/ryukinix/decorating           3

       num_comments        author        created_at
102             188      chase202   1/26/2016 18:17
103               1       _snydly    3/8/2016 10:39
144               1        zoodle   1/24/2016 19:01
196               1          kipi  12/11/2015 10:38
436               1  syslandscape   6/13/2016 16:23
...             ...           ...               ...
19597             1      bakery2k    7/9/2016 13:05
19852            18       aalhour   1/28/2016 14:55
19862           275     ngoldbaum   5/20/2016 15:14
19980             1   blacksmythe    9/18/2016 9:54
19998             1         lerax    5/20/2016 3:48

[160 rows x 7 columns]

In [87]:
print(df[df['title'].str.contains(r'JavaScript', case=True, regex=True)])

             id                                              title  \
267    12352636   Show HN: Hire JavaScript - Top JavaScript Talent
811    10741251  Ask HN: Are there any projects or compilers wh...
1046   11343334  If you write JavaScript tools or libraries, bu...
1093   10422726  Rollup.js: A next-generation JavaScript module...
1162   12461624               V8 JavaScript Engine: V8 Release 5.4
...         ...                                                ...
19349  11448301    Fotorama, a responsive JavaScript photo gallery
19548  12105148                 Another Kind of JavaScript Fatigue
19610  12203508  Lonely programmer detective uncovers the Mozil...
19885  12552131  Ask HN: Best Practices for CSS in a Modern Jav...
20069  12149183  Show HN: Parse recipe ingredients using JavaSc...

                                                     url  num_points  \
267                              https://www.hirejs.com/           1
811                                                  NaN           1
1046   https://medium.com/@Rich_Harris/how-to-not-bre...          48
1093                                 http://rollupjs.org          57
1162   http://v8project.blogspot.com/2016/09/v8-relea...         126
...                                                  ...         ...
19349                                http://fotorama.io/           1
19548  http://chrismm.com/blog/the-other-kind-of-java...           9
19610         http://stackoverflow.com/a/38677222/984780          29
19885                                                NaN           6
20069       https://github.com/herkyl/ingredients-parser           6

       num_comments          author        created_at
267               1        eibrahim   8/24/2016 15:16
811               2         ggonweb  12/15/2015 23:26
1046             19     callumlocke   3/23/2016 10:54
1093             17         dmmalam   10/21/2015 0:02
1162             19           okket    9/9/2016 12:46
...             ...             ...               ...
19349             1         alexkon    4/7/2016 15:59
19548             2    JacksCracked    7/16/2016 3:44
19610             8    luisperezphd    8/1/2016 16:07
19885             6        xwvvvvwx   9/21/2016 20:53
20069             2  zongitsrinzler   7/23/2016 11:35

[169 rows x 7 columns]